"""The stylesheet whose rules are data rather than design.

Two things on these pages are drawn from values the templates work out as they
render: the swatch for a bezel of a given shade and a given degree of yellowing,
and the length of a bar on the statistics page. Both were `style` attributes until
the content policy stopped allowing any (ADR-0022), and neither can be written by
hand in app.css -- one is mixed in Python from the colour vocabulary, and the
other is one rule per length a bar can be.

So they are generated here, once at import, and served as an ordinary stylesheet
from the app's own origin. What the markup carries is a class name, which is a
fact about the thing rather than an instruction about how to paint it.

The bar lengths go in half-percent steps. A bar's track is a few hundred pixels
wide, so half a percent is under two of them -- invisible, and the alternative is
a thousand rules to spare a difference nobody can see.
"""

from collections.abc import Iterator

from .common import _text_ver
from .entry import bezel_class, bezel_pairs

BAR_STEP = 5


def _bezel_rules() -> Iterator[str]:
    for colour, level, css in bezel_pairs():
        yield f".{bezel_class(colour, level)} {{ background: {css}; }}"


def _bar_rules() -> Iterator[str]:
    for tenths in range(0, 1000 + BAR_STEP, BAR_STEP):
        yield f".bars .fill.w-{tenths} {{ width: {tenths / 10:g}%; }}"


def _build() -> str:
    lines = [
        "/* Generated by app/datacss.py -- the rules whose values are data.",
        "   Edit the vocabulary or the generator, never this file: nothing writes it",
        "   to disk, it is built at import and served from memory. */",
        "",
        "/* A bezel's shade, and how far it has yellowed. */",
        *_bezel_rules(),
        "",
        "/* How long a bar on the statistics page is. */",
        *_bar_rules(),
        "",
    ]
    return "\n".join(lines)


DATA_CSS = _build()
DATA_CSS_VER = _text_ver(DATA_CSS)
