"""Write the design system's stylesheets from its data: `tokens.css` and one file per preset.

The colours of every preset, in both modes, and the scales every preset shares are
data -- `api/app/design/palettes.json` and `scales.json` -- because the contrast
tests read them as data (ADR-0024). Writing the same values into CSS by hand would
give two places to change a colour and a test that checks only one of them, so the
stylesheets are generated from the data and the suite runs this with `--check` to
hold the files on disk to what the data says.

Each mode's dark block is written twice: once under `[data-theme="dark"]` for the
visitor's toggle, and once inside `@media (prefers-color-scheme: dark)` for a
visitor who has not touched it. 0.1 kept those two in step by hand and had a test to
catch the day they drifted; generating both from one dictionary means they cannot.

    python tools/build_presets.py          # rewrite the files
    python tools/build_presets.py --check  # exit 1 if a file differs
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DESIGN = ROOT / "api" / "app" / "design"
OUT = ROOT / "api" / "app" / "static" / "css"
HEADER = "/* Generated by tools/build_presets.py from api/app/design/*.json -- edit the data, not this file. */\n"


def _decls(values: dict[str, str], indent: str = "  ") -> str:
    return "".join(f"{indent}--{name}: {value};\n" for name, value in values.items())


def _colours(palettes: dict, theme: str) -> dict[str, str]:
    """One preset-and-mode's colour tokens in the palette's own key order, plus its shadow."""
    colours = palettes["themes"][theme]
    return {
        **{key: colours[key] for key in palettes["keys"]},
        "shadow-pop": palettes["shadow_pop"][theme],
    }


def _scales(scales: dict) -> dict[str, str]:
    values: dict[str, str] = {}
    for family in ("spacing", "radius", "border", "size"):
        for token in scales[family]["tokens"]:
            values[token["name"]] = token["value"]
    for role, stack in scales["type"]["families"].items():
        values[f"font-{role}"] = stack
    # Nothing is drawn by these until a preset sets them; saying so here means a
    # component can use them without a fallback of its own.
    values.update(
        {
            "stripe-h": "0px",
            "stripe-image": "none",
            "flash": "none",
            "flash-w": "0px",
            "flash-inset": "0px",
        }
    )
    return values


def font_faces(scales: dict) -> str:
    """One `@font-face` per family and weight, served from the site itself.

    Latin only, and `swap`: the fallbacks in the family stacks are the system's own
    serif, sans and mono, so text is readable at once and the face arrives over it.
    The files come from this origin because the CSP allows nothing else (ADR-0021).
    """
    return "".join(
        "@font-face {\n"
        f'  font-family: "{font["family"]}";\n'
        "  font-style: normal;\n"
        f"  font-weight: {weight};\n"
        "  font-display: swap;\n"
        f'  src: url("/static/fonts/{font["folder"]}/{font["folder"]}-latin-{weight}.woff2")'
        ' format("woff2");\n'
        "}\n"
        for font in scales["type"]["fonts"]
        for weight in font["weights"]
    )


def tokens_css(palettes: dict, scales: dict) -> str:
    """The faces, the scales and the default preset: the page's tokens when no preset is chosen."""
    return (
        HEADER
        + font_faces(scales)
        + ":root {\n"
        + _decls(_scales(scales))
        + _decls(_colours(palettes, "light"))
        + "}\n"
        + ':root[data-theme="dark"] {\n'
        + _decls(_colours(palettes, "dark"))
        + "}\n"
        + "@media (prefers-color-scheme: dark) {\n"
        + "  :root:not([data-theme]) {\n"
        + _decls(_colours(palettes, "dark"), "    ")
        + "  }\n}\n"
    )


def preset_css(palettes: dict, preset: str) -> str:
    """One preset: what it changes besides colour and its light colours, then its dark ones.

    The selectors carry `:root` and the attribute, so a preset outranks the default's
    blocks in `tokens.css` whatever the order the files arrive in, and its dark block
    outranks its light one.
    """
    root = f':root[data-preset="{preset}"]'
    return (
        HEADER
        + f"{root} {{\n"
        + _decls(palettes["construction"][preset])
        + _decls(_colours(palettes, f"{preset}-light"))
        + "}\n"
        + f'{root}[data-theme="dark"] {{\n'
        + _decls(_colours(palettes, f"{preset}-dark"))
        + "}\n"
        + "@media (prefers-color-scheme: dark) {\n"
        + f"  {root}:not([data-theme]) {{\n"
        + _decls(_colours(palettes, f"{preset}-dark"), "    ")
        + "  }\n}\n"
    )


def outputs() -> dict[Path, str]:
    palettes = json.loads((DESIGN / "palettes.json").read_text(encoding="utf-8"))
    scales = json.loads((DESIGN / "scales.json").read_text(encoding="utf-8"))
    files = {OUT / "tokens.css": tokens_css(palettes, scales)}
    for preset in palettes["presets"]:
        if preset != "default":
            files[OUT / "presets" / f"{preset}.css"] = preset_css(palettes, preset)
    return files


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check", action="store_true", help="exit 1 if a generated file differs from the data"
    )
    args = parser.parse_args(argv)
    stale = []
    for path, text in outputs().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        if args.check:
            stale.append(path.relative_to(ROOT).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
    if stale:
        print("out of date with the design data (run tools/build_presets.py):", *stale, sep="\n  ")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
